apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-server
  namespace: prefect
spec:
  targetNamespace: prefect
  releaseName: prefect-server
  chart:
    spec:
      chart: prefect-server
      sourceRef:
        kind: HelmRepository
        name: prefect
        namespace: prefect
  interval: 5m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    server:
      prefectApiUrl: http://prefect.privatelink.uksouth.azmk8s.io/api
      image:
        prefectTag: 2.8.6-python3.11
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
    service:
      type: "LoadBalancer"
      port: 4200
      targetPort: 4200
      externalTrafficPolicy: "Cluster"
      annotations:
        "service.beta.kubernetes.io/azure-load-balancer-internal" : "true"
    ingress:
      enabled: true
      className: nginx
      host: 
        hostname: "prefect.privatelink.uksouth.azmk8s.io"
        pathType: "Prefix"
        path: /
      annotations:
        "nginx.ingress.kubernetes.io/ssl-redirect" : "true"

    postgresql:
      enabled: true
      auth:
        password: "Testing!23"