apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox-prefect.privatelink.uksouth.azmk8s.io-tls
  namespace: prefect
spec:
  isCA: true
  commonName: sandbox-prefect.privatelink.uksouth.azmk8s.io
  secretName: sandbox-prefect.privatelink.uksouth.azmk8s.io-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io