apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prefect.privatelink.uksouth.azmk8s.io-tls
  namespace: prefect
spec:
  isCA: true
  commonName: prefect.privatelink.uksouth.azmk8s.io
  secretName: ingress-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: sde
    kind: ClusterIssuer
    group: cert-manager.io